"""Derive the share-mandate reading of S1 that the contrail variants run on.

The third-edition S1 publishes SAF as production volumes, so its energy file holds
quantity mandates. Under a quantity mandate the SAF volume is fixed, and any extra
fuel a measure burns is fossil kerosene: a diversion strategy then raises CO2 by
proportionally more than it raises energy use, which says more about the way the
mandate is written than about the measure. Actual policies (ReFuelEU Aviation, the
UK and Brazilian mandates) set a blend share instead, so the extra fuel carries the
same SAF share as the rest.

The file written here is S1 with every quantity mandate rewritten as the equivalent
share mandate, the shares being the ones the uncoupled S1 realises, sampled from its
committed outputs. Without a measure it reproduces S1's SAF trajectory. It is the
same transform the coupled scenario uses (``aeromaps.utils.mandates``), without the
coupled scenario's 2026 kerosene price, which has no bearing on climate.

Run from this directory::

    python make_share_file.py
"""

import json
from pathlib import Path

from aeromaps.utils.mandates import quantity_to_share, realised_dropin_shares
from aeromaps.utils.scenarios import find_scenario

HERE = Path(__file__).resolve().parent
ATAG = HERE.parent
SOURCE_ENERGY = find_scenario("atag_3rd_edition_full").path / "data_inputs" / "s1_energy.yaml"
SOURCE_OUTPUTS = ATAG / "3rd_edition_full" / "data_outputs" / "s1.json"
CLIMATE_SCENARIO = find_scenario("atag_climate_analysis").path
SHARE_ENERGY = CLIMATE_SCENARIO / "data_inputs" / "s1_energy_share.yaml"
SHARE_CONFIG = CLIMATE_SCENARIO / "config_files" / "config_s1_share.yaml"

FIRST_YEAR = 2000

HEADER = """\
# GENERATED by make_share_file.py -- do not edit by hand.
#
# {source} with every quantity mandate rewritten as the equivalent share mandate,
# the shares being those the uncoupled S1 realises. The contrail variants run on
# it, so that the extra fuel a diversion burns carries the same SAF share as the rest.
"""

CONFIG = """\
# GENERATED by make_share_file.py -- do not edit by hand.
#
# Third-edition S1 with its SAF written as share mandates. Identical to
# atag_3rd_edition_full/config_files/config_s1.yaml except for the energy carriers
# file and the output path, so the committed edition results are never touched.
data:
  inputs:
    json_inputs_file: ../../atag_3rd_edition_full/data_inputs/s1_inputs.json
  outputs:
    json_outputs_file: ../data_outputs/s1_share.json
models:
  climate:
    climate_model_data_file: ../../climate_models/climate_model_fair_contrail_efficacy.yaml
  energy:
    energy_carriers_model_data_file: ../data_inputs/s1_energy_share.yaml
    resources_model_data_file: ../../atag_3rd_edition_full/data_inputs/resources.yaml
    processes_model_data_file: ../../atag_3rd_edition_full/data_inputs/processes.yaml
  standards:
  - models_traffic
  - models_efficiency_top_down_interp
  - models_energy_with_fuel_effect
  - models_energy_cost
  - models_emissions
  - models_offset
  - models_sustainability
  - models_operation_cost_top_down
  markets:
    markets_data_file: ../../markets/markets_central.yaml
"""


def main():
    realised = realised_dropin_shares(
        json.loads(SOURCE_OUTPUTS.read_text(encoding="utf-8")), SOURCE_ENERGY, FIRST_YEAR
    )
    quantity_to_share(SOURCE_ENERGY, realised, output_file=SHARE_ENERGY)
    body = SHARE_ENERGY.read_text(encoding="utf-8")
    SHARE_ENERGY.write_text(HEADER.format(source=SOURCE_ENERGY.name) + body, encoding="utf-8")
    SHARE_CONFIG.write_text(CONFIG, encoding="utf-8")
    print("wrote", SHARE_ENERGY.name, "and", SHARE_CONFIG.name)


if __name__ == "__main__":
    main()
