data:
  inputs:
    json_inputs_file: "../data_inputs/s3-TTW_inputs.json"
  outputs:
    json_outputs_file: "../data_outputs/s3-TTW.json"

models:
  climate:
    climate_model_data_file: default

  fleet:
    fleet_model_data_file: "../data_inputs/fleet_s3.yaml"
    aircraft_inventory_model_data_file: "../data_inputs/aircraft_inventory.yaml"

  energy:
    energy_carriers_model_data_file: "../data_inputs/s3_energy.yaml"
    resources_model_data_file: "../data_inputs/resources.yaml"
    processes_model_data_file: "../data_inputs/processes.yaml"

  standards:
    - models_traffic
    - models_efficiency_bottom_up
    - models_energy_without_fuel_effect
    - models_energy_cost
    - models_emissions
    - models_sustainability
    - models_operation_cost_bottom_up

  customs:
    atag_offset: "../models/atag_offset.py::ATAGOffset"
