repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.12.20"
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--no-default-groups", "--group", "doc", "--no-emit-project", "--no-hashes", "--output-file=docs/requirements.txt", "--format", "requirements-txt", "--quiet"]
        files: '^uv\.lock$'
  - repo: local
    hooks:
      # Ruff hooks are copied from https://github.com/astral-sh/ruff-pre-commit, but specifying
      # a local repo ensures using locked version of Ruff in uv.
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [ python, pyi, jupyter ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [ python, pyi, jupyter ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]

      - id: nbstripout
        name: nbstripout
        description: 'nbstripout: strip output from Jupyter and IPython notebooks'
        entry: nbstripout
        language: system
        types: [ jupyter ]
        require_serial: true
