[pytest]
testpaths = aeromaps/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
# Disabled nbmake and parallel execution for now to focus on unit tests
# addopts = --nbmake -v -n=auto