"""Derive the two energy files the coupled-demand scenario runs against.

Both are generated from the uncoupled third-edition S1 files rather than
maintained by hand, so a change upstream cannot leave them quietly stale. The
transforms themselves live in :mod:`aeromaps.utils.mandates`; what is specific to
this reproduction, and therefore stays here, is which files feed which and where
the shares are sampled from.

``s1_energy_share.yaml``
    S1 with every quantity mandate rewritten as the equivalent share mandate.
    A quantity mandate cannot be used with price-elastic demand: it makes the
    blend share depend on total demand, which is itself a coupling variable, and
    the MDA fails on the resulting coupling shape mismatch. It is also the wrong
    policy object, since holding a volume fixed while demand falls raises the
    blend share with no policy saying so. Real mandates (ReFuelEU Aviation, the
    UK and Brazilian schemes) are written as percentages.

    The shares are not invented: they are the ones the *uncoupled* S1 run
    actually realises, sampled from its committed outputs at each mandate's own
    anchor years, so with demand held exogenous this file reproduces S1's SAF
    trajectory exactly.

``s1_energy_nosaf.yaml``
    The same file with every drop-in SAF mandate zeroed, so fossil kerosene
    supplies the whole drop-in fleet. Alternative-aircraft carriers are left
    alone: S1's own ``*_electric_final_market_share`` is zero in every market, so
    their mandates are inert regardless, and zeroing them too would only be
    noise. This is the fuel-only counterfactual the demand response is read
    against.

Run from this directory::

    python make_energy_files.py
"""

import io
import json
from pathlib import Path

from aeromaps.utils.mandates import quantity_to_share, zero_mandates

HERE = Path(__file__).resolve().parent
ATAG = HERE.parent
SOURCE_ENERGY = ATAG / "3rd_edition_full" / "data_inputs" / "s1_energy.yaml"
SOURCE_OUTPUTS = ATAG / "3rd_edition_full" / "data_outputs" / "s1.json"
SHARE_FILE = HERE / "data_inputs" / "s1_energy_share.yaml"
NOSAF_FILE = HERE / "data_inputs" / "s1_energy_nosaf.yaml"

FIRST_YEAR = 2000

# Every drop-in pathway in the source file except fossil kerosene itself. Liquid
# hydrogen and battery electric are aircraft-type carriers, not drop-in fuel
# pathways, and are left out on purpose: see the module docstring.
DROPIN_SAF_PATHWAYS = (
    "hefa_oil_crops_trees",
    "atj_cellulosic_cover_crops",
    "hefa_waste_residue_lipids",
    "atj_agricultural_residues",
    "ft_woody_biomass",
    "ft_municipal_solid_waste",
    "atj_waste_gas",
    "electrofuel",
)

SHARE_HEADER = """\
# GENERATED by make_energy_files.py -- do not edit by hand.
#
# {source} with every quantity mandate rewritten as the equivalent share mandate.
# Shares are the ones the uncoupled S1 scenario realises, sampled from its committed
# outputs at each mandate's own anchor years, so with exogenous demand this reproduces
# S1's SAF trajectory exactly.
#
# Quantity mandates cannot be used with price-elastic demand: they make the blend share
# a function of total demand, which is itself a coupling variable, and the MDA fails with
# a coupling shape mismatch. See the module docstring of make_energy_files.py.
"""

NOSAF_HEADER = """\
# GENERATED by make_energy_files.py -- do not edit by hand.
#
# {source} with every drop-in SAF mandate zeroed, so fossil kerosene supplies the whole
# drop-in fleet. The fuel-only counterfactual the coupled demand response is read
# against; alternative-aircraft carriers are untouched and already inert.
"""


def realised_shares():
    """Share of drop-in energy carried by each carrier in the uncoupled S1 run."""
    outputs = json.loads(SOURCE_OUTPUTS.read_text(encoding="utf-8"))["vector_outputs"]
    years = list(range(FIRST_YEAR, FIRST_YEAR + len(outputs["energy_consumption_dropin_fuel"])))
    total = dict(zip(years, outputs["energy_consumption_dropin_fuel"]))
    shares = {}
    for column, series in outputs.items():
        if not column.endswith("_energy_consumption"):
            continue
        per_year = dict(zip(years, series))
        shares[column[: -len("_energy_consumption")]] = {
            year: (100.0 * per_year[year] / total[year] if total[year] else 0.0) for year in years
        }
    return shares


def _prepend(path, header):
    """Put the generated-by banner back, which the YAML writer does not carry."""
    body = io.open(path, encoding="utf-8").read()
    io.open(path, "w", encoding="utf-8", newline="").write(header + body)


def main():
    quantity_to_share(SOURCE_ENERGY, realised_shares(), output_file=SHARE_FILE)
    _prepend(SHARE_FILE, SHARE_HEADER.format(source=SOURCE_ENERGY.name))
    print("wrote %s" % SHARE_FILE.relative_to(ATAG))

    zero_mandates(SHARE_FILE, DROPIN_SAF_PATHWAYS, output_file=NOSAF_FILE)
    _prepend(NOSAF_FILE, NOSAF_HEADER.format(source=SHARE_FILE.name))
    print(
        "wrote %s (%d pathways zeroed)" % (NOSAF_FILE.relative_to(ATAG), len(DROPIN_SAF_PATHWAYS))
    )


if __name__ == "__main__":
    main()
