"""Derive a share-mandate energy file for the coupled-demand scenario.

The third-edition S1 energy file expresses its SAF mandates as fixed *quantities*.
That cannot be used with price-elastic demand, for two reasons:

1. **It breaks the solver.** A quantity mandate makes the SAF share depend on total
   demand, which is itself a coupling variable, and the resulting coupling structure
   is inconsistent between MDA initialisation and iteration -- GEMSEO's Gauss-Seidel
   step fails with a shape mismatch. Empirically: a share-only energy file converges,
   a file with two quantity mandates fails, and the full nine-quantity file fails with
   a larger mismatch still.
2. **It is the wrong policy object.** Holding a SAF volume fixed while demand responds
   to price means the blend share rises on its own as demand falls, without any policy
   saying so, and can exceed what the fleet can burn. Real mandates (ReFuelEU Aviation,
   the UK and Brazilian schemes) are specified as percentages.

So the coupled scenario uses shares. The shares are not invented: they are the ones the
uncoupled S1 scenario actually realises, read from its committed outputs, so with demand
held exogenous this file reproduces S1's SAF trajectory. Under coupling, SAF volume then
scales with demand at a fixed blend percentage, which is what a percentage mandate does.

Run from this directory to regenerate ``data_inputs/s1_energy_share.yaml``::

    python make_share_mandates.py
"""

import json
from pathlib import Path

import yaml

import aeromaps.utils.yaml  # noqa: F401  (registers the !AeroMapsCustomDataType tag)
from aeromaps.models.base import AeroMapsCustomDataType

HERE = Path(__file__).resolve().parent
ATAG = HERE.parent
SOURCE_ENERGY = ATAG / "3rd_edition_full" / "data_inputs" / "s1_energy.yaml"
SOURCE_OUTPUTS = ATAG / "3rd_edition_full" / "data_outputs" / "s1.json"
TARGET = HERE / "data_inputs" / "s1_energy_share.yaml"

HEADER = """\
# GENERATED by make_share_mandates.py -- do not edit by hand.
#
# {source} with every quantity mandate rewritten as the equivalent share mandate.
# Shares are the ones the uncoupled S1 scenario realises, sampled from its committed
# outputs at each mandate's own anchor years, so with exogenous demand this reproduces
# S1's SAF trajectory exactly.
#
# Quantity mandates cannot be used with price-elastic demand: they make the blend share
# a function of total demand, which is itself a coupling variable, and the MDA fails with
# a coupling shape mismatch. See the module docstring of make_share_mandates.py.
"""


def realised_shares():
    """Annual share of drop-in energy carried by each carrier in the uncoupled S1 run."""
    data = json.loads(SOURCE_OUTPUTS.read_text())["vector_outputs"]
    years = list(range(2000, 2000 + len(data["energy_consumption_dropin_fuel"])))
    total = dict(zip(years, data["energy_consumption_dropin_fuel"]))
    shares = {}
    for column, series in data.items():
        if not column.endswith("_energy_consumption"):
            continue
        carrier = column[: -len("_energy_consumption")]
        per_year = dict(zip(years, series))
        shares[carrier] = {
            year: (100.0 * per_year[year] / total[year] if total[year] else 0.0)
            for year in years
        }
    return shares


def main():
    document = yaml.load(SOURCE_ENERGY.read_text(), Loader=yaml.Loader)
    shares = realised_shares()

    converted = []
    for carrier, spec in document.items():
        mandate = (spec.get("inputs") or {}).get("mandate")
        if not mandate or mandate.get("mandate_type") != "quantity":
            continue
        quantity = mandate.pop("mandate_quantity")
        if carrier not in shares:
            raise KeyError(f"no realised share for {carrier!r} in {SOURCE_OUTPUTS.name}")
        anchors = [int(year) for year in quantity.years]
        mandate["mandate_type"] = "share"
        mandate["mandate_share"] = AeroMapsCustomDataType(
            {
                "years": anchors,
                "values": [round(shares[carrier][year], 10) for year in anchors],
                "method": quantity.method,
            }
        )
        converted.append(carrier)

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.dump(document, sort_keys=False, default_flow_style=False)
    TARGET.write_text(HEADER.format(source=SOURCE_ENERGY.name) + body)

    print(f"converted {len(converted)} quantity mandates -> share:")
    for carrier in converted:
        print(f"  {carrier}")
    print(f"wrote {TARGET.relative_to(ATAG)}")


if __name__ == "__main__":
    main()
