"""Build low/high traffic variants that mean something on a 2024 baseline.

The shared ``markets_low.yaml`` / ``markets_high.yaml`` encode the second edition's
growth, where the spread between low, central and high lived almost entirely in the
COVID trough and the recovery that followed: low dropped to 59 % of reference and then
climbed back with high catch-up rates. Once traffic is pinned to observed data through
2023, that trough never happens, ``covid_end_year_reference_ratio`` goes inert, and only
the catch-up rates survive -- applied to the real 2023 level. The result inverts the
ordering: low becomes the *highest* trajectory.

Those files stay as they are, because the second edition runs from 2020 where they are
still correct. For the third edition this module builds separate files on a different
principle:

* all three variants share the central trajectory up to and including the prospection
  start year, so they begin from the same observed traffic;
* from the year after, each follows ``alpha * central_growth(t)``;
* ``alpha`` is solved so 2050 traffic lands on the second edition's published figure for
  that variant -- 15.20 T RPK for low, 24.01 T for high (recovered from the outputs
  committed before the re-baselining).

Run from this directory::

    python make_traffic_variants.py
"""

from pathlib import Path

import yaml

import aeromaps.utils.yaml  # noqa: F401  (registers the !AeroMapsCustomDataType tag)
from aeromaps import create_process
from aeromaps.utils.traffic_variants import scale_growth_after, solve_scale_for_target

HERE = Path(__file__).resolve().parent
ATAG = HERE.parent
MARKETS = ATAG / "markets"
CENTRAL = MARKETS / "markets_central.yaml"
GENERATED = HERE / "_generated"

# 2050 RPK targets, from the second-edition outputs as committed before 45c8b890.
TARGETS = {"low": 15.20e12, "high": 24.01e12}

# Growth is carried per market, not by the defaults block. Only the passenger markets
# declare one; freight is driven by its reference block alone.
GROWTH_MARKETS = ("short_range", "medium_range", "long_range")

HEADER = """\
# GENERATED by 3rd_edition_variants/make_traffic_variants.py -- do not edit by hand.
#
# {variant} traffic for the third edition, on the 2024 observed baseline.
# Identical to markets_central.yaml through {pivot}, then every market's growth rate is
# scaled by alpha = {alpha:.6f} so that 2050 RPK reaches {target:.2f} trillion -- the
# second edition's published {variant} figure.
#
# The legacy markets_{variant}.yaml is NOT used here: its spread lives in a COVID trough
# that the observed-data baseline removes, which inverts the low/high ordering. See the
# module docstring of make_traffic_variants.py.
"""


def scaled_markets(alpha: float, pivot: int) -> dict:
    """Central markets with growth scaled by ``alpha`` after ``pivot``."""
    document = yaml.load(CENTRAL.read_text(), Loader=yaml.Loader)
    return scale_growth_after(document, alpha, pivot, markets=GROWTH_MARKETS)


def write_markets(document: dict, path: Path, variant: str, alpha: float, pivot: int) -> Path:
    body = yaml.dump(document, sort_keys=False, default_flow_style=False)
    header = HEADER.format(
        variant=variant, alpha=alpha, pivot=pivot, target=TARGETS[variant] / 1e12
    )
    path.write_text(header + body)
    return path


def rpk_2050(markets_path: Path) -> float:
    """2050 RPK for the central S1 scenario run against ``markets_path``."""
    GENERATED.mkdir(exist_ok=True)
    config = GENERATED / f"_calib_{markets_path.stem}.yaml"
    full = "../../3rd_edition_full/data_inputs"
    config.write_text(
        yaml.safe_dump(
            {
                "data": {"inputs": {"json_inputs_file": f"{full}/s1_inputs.json"}},
                "models": {
                    "climate": {"climate_model_data_file": "default"},
                    "energy": {
                        "energy_carriers_model_data_file": f"{full}/s1_energy.yaml",
                        "resources_model_data_file": f"{full}/resources.yaml",
                        "processes_model_data_file": f"{full}/processes.yaml",
                    },
                    "standards": yaml.safe_load(
                        (ATAG / "3rd_edition_full/config_files/config_s1.yaml").read_text()
                    )["models"]["standards"],
                    "markets": {"markets_data_file": f"../../markets/{markets_path.name}"},
                },
            },
            sort_keys=False,
        )
    )
    process = create_process(configuration_file=str(config))
    process.compute()
    return float(process.data["vector_outputs"].loc[2050, "rpk"])


def solve_alpha(variant: str, pivot: int, tol: float = 5e-4, max_iter: int = 12) -> float:
    """Secant search for the alpha that lands 2050 RPK on the variant's target."""
    target = TARGETS[variant]
    path = MARKETS / f"markets_{variant}_3rd.yaml"

    def evaluate(alpha: float) -> float:
        # Each candidate is written before it is run, since the scenario reads
        # its markets from disk; the winning file is therefore already in place
        # except when the search stops on a factor it did not evaluate last.
        write_markets(scaled_markets(alpha, pivot), path, variant, alpha, pivot)
        value = rpk_2050(path)
        print(
            f"    alpha={alpha:.6f} -> 2050 RPK {value / 1e12:6.3f} T (target {target / 1e12:.2f})"
        )
        return value

    bracket = (0.65, 1.05) if variant == "low" else (1.05, 1.40)
    alpha = solve_scale_for_target(evaluate, target, bracket, tol=tol, max_iter=max_iter)
    write_markets(scaled_markets(alpha, pivot), path, variant, alpha, pivot)
    return alpha


def main():
    process = create_process(
        configuration_file=str(ATAG / "3rd_edition_full/config_files/config_s1.yaml")
    )
    pivot = int(process.parameters.prospection_start_year)
    print(f"prospection start (pivot year, growth unscaled up to here): {pivot}")

    for variant in ("low", "high"):
        print(f"\nsolving alpha for {variant} (target {TARGETS[variant] / 1e12:.2f} T):")
        alpha = solve_alpha(variant, pivot)
        print(f"  -> markets_{variant}_3rd.yaml written with alpha = {alpha:.6f}")


if __name__ == "__main__":
    main()
