data:
  inputs:
    json_inputs_file: "../data_inputs/s2-low_inputs.json"
  outputs:
    json_outputs_file: "../data_outputs/s2-low.json"

models:
  climate:
    climate_model_data_file: default

  energy:
    energy_carriers_model_data_file: "../data_inputs/s2_energy.yaml"
    resources_model_data_file: "../data_inputs/resources.yaml"
    processes_model_data_file: "../data_inputs/processes.yaml"

  standards:
    - models_traffic
    - models_efficiency_top_down_interp
    - models_energy_with_fuel_effect
    - models_emissions
    - models_sustainability
    - models_energy_cost
    - models_operation_cost_top_down

  customs:
    atag_offset: "../models/atag_offset.py::ATAGOffset"