data:
  inputs:
    json_inputs_file: "../data_inputs/s1_central_inputs.json"
  outputs:
    json_outputs_file: "./outputs.json"

models:
  energy:
    energy_carriers_model_data_file: "../data_inputs/s1_central_energy_inputs_TD.yaml"
    resources_model_data_file: "../data_inputs/s1_central_resources_data_TD.yaml"
    processes_model_data_file: "../data_inputs/processes_data.yaml"

  standards:
    - models_traffic
    - models_efficiency_top_down
    - models_energy_without_fuel_effect
    - models_energy_cost
    - models_emissions

  customs:
    atag_offset: "../models/atag_offset.py::ATAGOffset"