excel_data_file: "../resources/data/data.xlsx"
excel_data_information_file: "../resources/data/data_information.csv"
parameters_json_data_file: "../resources/data/parameters.json"
parameters_energy_carriers_data_file: "../resources/data/energy_carriers_data.yaml"
outputs_json_data_file: "../resources/data/outputs.json"
parameters_climate_data_file: "../resources/climate_data/temperature_historical_dataset.csv"