EXCEL_DATA_FILE: "${oc.env:SCRIPT_DIR}/resources/data/data.xlsx"
EXCEL_DATA_INFORMATION_FILE: "${oc.env:SCRIPT_DIR}/resources/data/data_information.csv"
PARAMETERS_JSON_DATA_FILE: "${oc.env:SCRIPT_DIR}/resources/data/parameters.json"
PARAMETERS_ENERGY_CARRIERS_DATA_FILE: "${oc.env:SCRIPT_DIR}/resources/data/energy_carriers_data.yaml"
OUTPUTS_JSON_DATA_FILE: "${oc.env:SCRIPT_DIR}/resources/data/outputs.json"
PARAMETERS_CLIMATE_DATA_FILE: "${oc.env:SCRIPT_DIR}/resources/climate_data/temperature_historical_dataset.csv"