"""Derive the tank-to-wake twins of the third-edition energy and process files.

The reports headline tank-to-wake (TtW) emissions while this reproduction runs
well-to-wake (WtW), so both scopes have to be available from committed outputs.
The report states the method it uses::

    The role of SAF in this analysis is based on the ICAO CORSIA methodology,
    which reflects the combustion-related emissions portion (3.16 gCO2/gfuel) of
    life cycle values ... within this methodology, a majority of the life cycle
    emissions reductions from SAF that occur in the well to tank (WtT) phase are
    accounted for as TtW reductions.

So a pathway's TtW factor is the fossil combustion baseline scaled by that
pathway's carbon-intensity ratio::

    TtW = FOSSIL_TTW x (CI_pathway / FOSSIL_WTW)

which is the method the second edition's committed ``*-TTW_energy.yaml`` files
already use: its electrofuel reads 7.38, exactly 73.8 x 0.10, and its woody
biomass 6.642, exactly 73.8 x 0.09. Taking the ratio rather than the report's
rounded percentages avoids importing their rounding: woody biomass at 2050 comes
out at 5.9905 rather than 73.8 x 0.08 = 5.904.

Carriers that are not drop-in fuels are not combusted, so their TtW factor is
zero: the carbon behind a battery-electric or electrolysis-derived pathway is
well-to-tank by definition. The processes that feed them are zeroed for the same
reason, which is what ``processes-TTW.yaml`` is for. The resources need no twin
here, since the third edition's ``resources.yaml`` already carries a zero factor
for green electricity.

Note ``FOSSIL_TTW`` is 73.8 and not the 71.81 that 3.16 gCO2/g over 44 MJ/kg
gives. 73.8 is the value both editions' existing files already carry, and this
script keeps it so the two editions stay comparable; the discrepancy is the
data's, not this transform's.

Run from this directory::

    python make_ttw_twins.py
"""

import io
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent

FOSSIL_WTW = 88.7  # gCO2/MJ, the report's fossil-kerosene carbon intensity
FOSSIL_TTW = 73.8  # gCO2/MJ, combustion only
RATIO = FOSSIL_TTW / FOSSIL_WTW

EF_KEY = "mean_co2_emission_factor_without_resource"

# (source, twin) pairs, relative to this directory.
ENERGY_TWINS = [
    (
        "3rd_edition_full/data_inputs/s1_energy.yaml",
        "3rd_edition_full/data_inputs/s1-TTW_energy.yaml",
    ),
    (
        "3rd_edition_full/data_inputs/s2_energy.yaml",
        "3rd_edition_full/data_inputs/s2-TTW_energy.yaml",
    ),
    (
        "3rd_edition_light/data_inputs/s0_energy.yaml",
        "3rd_edition_light/data_inputs/s0-TTW_energy.yaml",
    ),
]
PROCESS_TWINS = [
    (
        "3rd_edition_full/data_inputs/processes.yaml",
        "3rd_edition_full/data_inputs/processes-TTW.yaml",
    ),
]

HEADER = """# Tank-to-wake twin of {source}, generated by make_ttw_twins.py.
# Do not edit by hand: edit the well-to-wake file and regenerate.
#
# Drop-in pathways carry the fossil combustion baseline ({ttw} gCO2/MJ) scaled by
# their carbon-intensity ratio against fossil kerosene ({wtw} gCO2/MJ), which is
# the CORSIA accounting the report describes and the method the second edition's
# TTW files already use. Everything not combusted reads zero: its carbon is
# well-to-tank. Nothing else differs from the source file.
"""


def top_level_blocks(text):
    """Yield (name, start, end) for each top-level YAML block."""
    starts = [(m.group(1), m.start()) for m in re.finditer(r"^(\S+):[ \t]*$", text, re.M)]
    for i, (name, start) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
        yield name, start, end


def fmt(value):
    """Four decimals is far finer than the one to three the sources carry."""
    text = ("%.4f" % value).rstrip("0")
    return text + "0" if text.endswith(".") else text


def rewrite_factor(block, transform, zeroing):
    """Rewrite the values of this block's own emission-factor curve in place,
    handling both the inline and the block-list flavours the repo uses."""
    key = re.search(r"^([ \t]*)%s:.*$" % re.escape(EF_KEY), block, re.M)
    if key is None:
        return block, False
    rest = block[key.end() :]

    inline = re.search(r"^([ \t]*)values:[ \t]*\[([^\]]*)\]", rest, re.M)
    listed = re.search(
        r"^([ \t]*)values:[ \t]*\n((?:[ \t]*-[ \t]*[-\d.eE+]+[ \t]*\n)+)", rest, re.M
    )
    if inline is not None and (listed is None or inline.start() < listed.start()):
        numbers = [n for n in inline.group(2).split(",") if n.strip()]
        body = ", ".join(fmt(transform(float(n))) for n in numbers)
        new = "%svalues: [%s]" % (inline.group(1), (" %s " % body) if body else "")
        tail = rest[inline.end() :]
        if zeroing:
            # any trailing comment described the well-to-wake value it replaced
            tail = tail[tail.index("\n") :]
        return block[: key.end()] + rest[: inline.start()] + new + tail, True
    if listed is not None:
        lines = []
        for line in listed.group(2).splitlines():
            indent, number = re.match(r"^([ \t]*-[ \t]*)([-\d.eE+]+)[ \t]*$", line).groups()
            lines.append("%s%s" % (indent, fmt(transform(float(number)))))
        new = "%svalues:\n%s\n" % (listed.group(1), "\n".join(lines))
        return block[: key.end()] + rest[: listed.start()] + new + rest[listed.end() :], True
    return block, False


def to_ttw_energy(text):
    out, scaled, zeroed = [], [], []
    for name, start, end in top_level_blocks(text):
        block = text[start:end]
        dropin = re.search(r"^\s*aircraft_type:\s*[\"']?dropin_fuel[\"']?\s*$", block, re.M)
        transform = (lambda v: v * RATIO) if dropin else (lambda v: 0.0)
        block, touched = rewrite_factor(block, transform, zeroing=not dropin)
        if touched:
            (scaled if dropin else zeroed).append(name)
        out.append(block)
    return "".join(out), scaled, zeroed


def to_ttw_processes(text):
    out, zeroed = [], []
    for name, start, end in top_level_blocks(text):
        block, touched = rewrite_factor(text[start:end], lambda v: 0.0, zeroing=True)
        if touched:
            zeroed.append(name)
        out.append(block)
    return "".join(out), [], zeroed


def transform_file(source_rel, target_rel, convert):
    source, target = HERE / source_rel, HERE / target_rel
    with io.open(source, encoding="utf-8", newline="") as handle:
        raw = handle.read()
    newline = "\r\n" if "\r\n" in raw else "\n"
    body, scaled, zeroed = convert(raw.replace("\r\n", "\n"))
    header = HEADER.format(source=source.name, ttw=FOSSIL_TTW, wtw=FOSSIL_WTW)
    with io.open(target, "w", encoding="utf-8", newline=newline) as handle:
        handle.write(header + body)
    print("wrote %s" % target_rel)
    if scaled:
        print("  scaled: %s" % ", ".join(scaled))
    if zeroed:
        print("  zeroed: %s" % ", ".join(zeroed))


def main():
    for source_rel, target_rel in ENERGY_TWINS:
        transform_file(source_rel, target_rel, to_ttw_energy)
    for source_rel, target_rel in PROCESS_TWINS:
        transform_file(source_rel, target_rel, to_ttw_processes)


if __name__ == "__main__":
    main()
