name: Build PyPI package

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  build-publish-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build AeroMAPS
        run: uv build


      - name: publish AeroMAPS to PyPI
        env:
          TOKEN: ${{ secrets.PYPI }} # do not use the secret directly in run command, it would write it plainly in the log
        run: uv publish